question_data = [
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "In which city, is the Big Nickel located in Canada?",
     "correct_answer": "Sudbury, Ontario",
     "incorrect_answers": ["Calgary, Alberta", "Halifax, Nova Scotia ",
                           "Victoria, British Columbia"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "The body of the Egyptian Sphinx was based on which animal?",
     "correct_answer": "Lion", "incorrect_answers": ["Bull", "Horse", "Dog"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Montreal is in which Canadian province?", "correct_answer": "Quebec",
     "incorrect_answers": ["Ontario", "Nova Scotia", "Alberta"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "What state is the largest state of the United States of America?",
     "correct_answer": "Alaska",
     "incorrect_answers": ["California", "Texas", "Washington"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "What is the capital of Indonesia?", "correct_answer": "Jakarta",
     "incorrect_answers": ["Bandung", "Medan", "Palembang"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Which of these countries is &quot;doubly landlocked&quot; (surrounded entirely by one or more landlocked countries)?",
     "correct_answer": "Uzbekistan",
     "incorrect_answers": ["Switzerland", "Bolivia", "Ethiopia"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "How many counties in the Republic of Ireland.",
     "correct_answer": "26", "incorrect_answers": ["32", "28", "30"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Which city is the capital of Switzerland?", "correct_answer": "Bern",
     "incorrect_answers": ["Z&uuml;rich", "Frankfurt", "Wien"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Which European city has the highest mileage of canals in the world?",
     "correct_answer": "Birmingham",
     "incorrect_answers": ["Venice", "Amsterdam", "Berlin"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "What is the only state in the United States that does not have a flag in a shape with 4 edges?",
     "correct_answer": "Ohio",
     "incorrect_answers": ["Florida", "Idaho", "New Mexico"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Which of the following countries does NOT recognize Armenia as an independent country?",
     "correct_answer": "Pakistan",
     "incorrect_answers": ["Iran", "Turkey", "Azerbaijan"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "On which continent is the country of Angola located?",
     "correct_answer": "Africa",
     "incorrect_answers": ["South America", "Europe", "Asia"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following languages does NOT use the Latin alphabet?",
     "correct_answer": "Georgian",
     "incorrect_answers": ["Turkish", "Swahili", "Vietnamese"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Which of these countries is NOT located in Africa?",
     "correct_answer": "Suriname",
     "incorrect_answers": ["Burkina Faso", "Mozambique", "Algeria"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "The Japanese district Akihabara is also known by what nickname?",
     "correct_answer": "Electric Town",
     "incorrect_answers": ["Moon Walk River", "Otaku Central ", "Big Eyes"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the capital of the US state Nevada?",
     "correct_answer": "Carson City",
     "incorrect_answers": ["Las Vegas", "Henderson", "Reno"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the capital of the State of Washington, United States?",
     "correct_answer": "Olympia",
     "incorrect_answers": ["Washington D.C.", "Seattle", "Yukon"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "Which of the following Arab countries does NOT have a flag containing only Pan-Arab colours?",
     "correct_answer": "Qatar",
     "incorrect_answers": ["Kuwait", "United Arab Emirates", "Jordan"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "Which of these is the name of the largest city in the US state Tennessee?",
     "correct_answer": "Memphis",
     "incorrect_answers": ["Thebes", "Alexandria", "Luxor"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Which German city is located on the River Isar?",
     "correct_answer": "Munich",
     "incorrect_answers": ["Berlin", "Hamburg", "Dortmund"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What year is on the flag of the US state Wisconsin?",
     "correct_answer": "1848", "incorrect_answers": ["1634", "1783", "1901"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "What is the Capital of the United States?",
     "correct_answer": "Washington, D.C.",
     "incorrect_answers": ["Los Angelas, CA", "New York City, NY", "Houston, TX"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "Llanfair&shy;pwllgwyngyll&shy;gogery&shy;chwyrn&shy;drobwll&shy;llan&shy;tysilio&shy;gogo&shy;goch is located on which Welsh island?",
     "correct_answer": "Anglesey",
     "incorrect_answers": ["Barry", "Bardsey", "Caldey"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What is the most populous Muslim-majority nation in 2010?",
     "correct_answer": "Indonesia",
     "incorrect_answers": ["Saudi Arabia", "Iran", "Sudan"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "The towns of Brugelette, Arlon and Ath are located in which country?",
     "correct_answer": "Belgium",
     "incorrect_answers": ["Andorra", "France", "Luxembourg"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "How tall is One World Trade Center in New York City?",
     "correct_answer": "1,776 ft",
     "incorrect_answers": ["1,888 ft", "1,225 ft", "1,960 ft"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the busiest port in Europe?",
     "correct_answer": "Port of Rotterdam",
     "incorrect_answers": ["Port of Antwerp", "Port of Hamburg", "Port of Amsterdam"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Which Canadian province has Charlottetown as its capital?",
     "correct_answer": "Prince Edward Island",
     "incorrect_answers": ["Saskachewan", "Northwest Terrirories", "Ontario"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "What is Canada&#039;s smallest province?",
     "correct_answer": "Prince Edward Island",
     "incorrect_answers": ["New Brunswick", "Nova Scotia", "Yukon"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What is the tallest mountain in Canada?",
     "correct_answer": "Mount Logan",
     "incorrect_answers": ["Mont Tremblant", "Whistler Mountain", "Blue Mountain"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the capital of Seychelles?", "correct_answer": "Victoria",
     "incorrect_answers": ["Luanda", "N&#039;Djamena", "Tripoli"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "The land mass of modern day Turkey is called what?",
     "correct_answer": "Anatolia",
     "incorrect_answers": ["Ismuth of Ottoma", "Ottoma", "Ismuth of Anatolia"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "How many timezones does Russia have?", "correct_answer": "11",
     "incorrect_answers": ["6", "24", "16"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "In the 2016 Global Peace Index poll, out of 163 countries, what was the United States of America ranked?",
     "correct_answer": "103", "incorrect_answers": ["10", "59", "79"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the highest mountain in the world?",
     "correct_answer": "Mt. Everest",
     "incorrect_answers": ["Mount Godwin Austen", "Kangchenjunga", "Annapurna"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "Norway has a larger land area than Sweden.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What was the most populous city in the Americas in 2015?",
     "correct_answer": "S&atilde;o Paulo",
     "incorrect_answers": ["New York", "Mexico City", "Los Angeles"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the capital of Estonia?", "correct_answer": "Tallinn",
     "incorrect_answers": ["Helsinki", "Tartu", "Riga"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "Which ocean borders the west coast of the United States?",
     "correct_answer": "Pacific",
     "incorrect_answers": ["Atlantic", "Indian", "Arctic"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "What is the most common climbing route for the second highest mountain in the world, K2?",
     "correct_answer": "Abruzzi Spur",
     "incorrect_answers": ["Magic Line", "Cesen Route", "Polish Line"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the capital of Lithuania?", "correct_answer": "Vilnius",
     "incorrect_answers": ["Tallinn", "Helsinki", "Riga"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "How many rivers are in Saudi Arabia?", "correct_answer": "0",
     "incorrect_answers": ["1", "2", "3"]},
    {"category": "Geography", "type": "boolean", "difficulty": "hard",
     "question": "The two largest ethnic groups of Belgium are Flemish and Walloon. ",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "medium",
     "question": "The title of the 1969 film &quot;Krakatoa, East_of Java&quot; is incorrect, as Krakatoa is in fact west of Java.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "Frankenmuth, a US city nicknamed &quot;Little Bavaria&quot;, is located in what state?",
     "correct_answer": "Michigan",
     "incorrect_answers": ["Pennsylvania", "Kentucky", "Virginia"]},
    {"category": "Geography", "type": "multiple", "difficulty": "medium",
     "question": "What is the capital of Greenland?", "correct_answer": "Nuuk",
     "incorrect_answers": ["Sisimiut", "Narsaq", "Maniitsoq"]},
    {"category": "Geography", "type": "multiple", "difficulty": "hard",
     "question": "Which of these is NOT a real tectonic plate?",
     "correct_answer": "Atlantic Plate",
     "incorrect_answers": ["North American Plate", "Eurasian Plate", "Nazca Plate"]},
    {"category": "Geography", "type": "multiple", "difficulty": "easy",
     "question": "Greenland is a part of which kingdom?", "correct_answer": "Denmark",
     "incorrect_answers": ["Sweden", "Norway", "United Kingdom"]}
]
